import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { NextThemeProvider } from "@/lib/NextThemeProvider";


const poppins = Poppins({ subsets: ["latin"], weight: '400' }); 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
       <html lang="en">
      <body className={poppins.className}>
        <NextThemeProvider>
        {children}
        </NextThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
